package Model;
// Generated 6/09/2021 07:08:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Integer idAlbum;
     private Grupo grupo;
     private String nombre;
     private Integer noCanciones;
     private Date duracion;
     private Date lanzamiento;
     private Double noVentas;
     private String genero;
     private Set<Canciones> cancioneses = new HashSet<Canciones>(0);

    public Album() {
        grupo = new Grupo();
    }

    public Album(Grupo grupo, String nombre, Integer noCanciones, Date duracion, Date lanzamiento, Double noVentas, String genero, Set<Canciones> cancioneses) {
       this.grupo = grupo;
       this.nombre = nombre;
       this.noCanciones = noCanciones;
       this.duracion = duracion;
       this.lanzamiento = lanzamiento;
       this.noVentas = noVentas;
       this.genero = genero;
       this.cancioneses = cancioneses;
    }
   
    public Integer getIdAlbum() {
        return this.idAlbum;
    }
    
    public void setIdAlbum(Integer idAlbum) {
        this.idAlbum = idAlbum;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNoCanciones() {
        return this.noCanciones;
    }
    
    public void setNoCanciones(Integer noCanciones) {
        this.noCanciones = noCanciones;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public Date getLanzamiento() {
        return this.lanzamiento;
    }
    
    public void setLanzamiento(Date lanzamiento) {
        this.lanzamiento = lanzamiento;
    }
    public Double getNoVentas() {
        return this.noVentas;
    }
    
    public void setNoVentas(Double noVentas) {
        this.noVentas = noVentas;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Set<Canciones> getCancioneses() {
        return this.cancioneses;
    }
    
    public void setCancioneses(Set<Canciones> cancioneses) {
        this.cancioneses = cancioneses;
    }




}


