package Model;
// Generated 6/09/2021 07:08:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private String nombre;
     private String apellidoP;
     private String apellidoM;
     private String nombreArtistico;
     private Integer edad;
     private Character genero;
     private Date fechaNacimiento;
     private String pais;
     private String instrumento;
     private Double estatura;
     private Set<Canciones> cancioneses = new HashSet<Canciones>(0);

    public Artista() {
    }

    public Artista(String nombre, String apellidoP, String apellidoM, String nombreArtistico, Integer edad, Character genero, Date fechaNacimiento, String pais, String instrumento, Double estatura, Set<Canciones> cancioneses) {
       this.nombre = nombre;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.nombreArtistico = nombreArtistico;
       this.edad = edad;
       this.genero = genero;
       this.fechaNacimiento = fechaNacimiento;
       this.pais = pais;
       this.instrumento = instrumento;
       this.estatura = estatura;
       this.cancioneses = cancioneses;
    }
   
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getNombreArtistico() {
        return this.nombreArtistico;
    }
    
    public void setNombreArtistico(String nombreArtistico) {
        this.nombreArtistico = nombreArtistico;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Character getGenero() {
        return this.genero;
    }
    
    public void setGenero(Character genero) {
        this.genero = genero;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getInstrumento() {
        return this.instrumento;
    }
    
    public void setInstrumento(String instrumento) {
        this.instrumento = instrumento;
    }
    public Double getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(Double estatura) {
        this.estatura = estatura;
    }
    public Set<Canciones> getCancioneses() {
        return this.cancioneses;
    }
    
    public void setCancioneses(Set<Canciones> cancioneses) {
        this.cancioneses = cancioneses;
    }




}


