package Model;
// Generated 6/09/2021 07:08:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Disquera disquera;
     private String nombre;
     private String origen;
     private Date inicio;
     private Integer noIntegrantes;
     private String genero;
     private String idioma;
     private Set<Album> albums = new HashSet<Album>(0);
     private Set<Canciones> cancioneses = new HashSet<Canciones>(0);

    public Grupo() {
        disquera = new Disquera();
    }

    public Grupo(Disquera disquera, String nombre, String origen, Date inicio, Integer noIntegrantes, String genero, String idioma, Set<Album> albums, Set<Canciones> cancioneses) {
       this.disquera = disquera;
       this.nombre = nombre;
       this.origen = origen;
       this.inicio = inicio;
       this.noIntegrantes = noIntegrantes;
       this.genero = genero;
       this.idioma = idioma;
       this.albums = albums;
       this.cancioneses = cancioneses;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Disquera getDisquera() {
        return this.disquera;
    }
    
    public void setDisquera(Disquera disquera) {
        this.disquera = disquera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Integer getNoIntegrantes() {
        return this.noIntegrantes;
    }
    
    public void setNoIntegrantes(Integer noIntegrantes) {
        this.noIntegrantes = noIntegrantes;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }
    public Set<Canciones> getCancioneses() {
        return this.cancioneses;
    }
    
    public void setCancioneses(Set<Canciones> cancioneses) {
        this.cancioneses = cancioneses;
    }




}


